name: AutoMerge

on:
  pull_request:
    branches:
      - master

jobs:
  automerge:
    if: github.event.review.state == 'approved' || !github.event.review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3.0.0
        with:
          github-toke: ${{github.token}}
          script: |
            github.pullRequests.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number 
            })
